import React, { useState, useMemo } from "react";
import { Link } from "react-router-dom";
import {
  FaRobot,
  FaDumbbell,
  FaComments,
  FaAppleAlt,
  FaBullseye,
  FaCalculator,
  FaFire,
  FaStar,
  FaTrophy,
  FaShoppingCart,
  FaVolumeUp,
  FaVolumeMute,
  FaCopy,
  FaCheck,
  FaUndo,
  FaLightbulb,
  FaBolt,
  FaHeartbeat,
  FaPaperPlane,
  FaCheckSquare,
  FaSquare,
  FaRunning,
} from "react-icons/fa";

import { useCart } from "../context/CartContext";
import { products } from "../data/products";
import {
  COACH_PERSONAS,
  PRO_DRILLS,
  TRAINING_PLANS_BY_SPORT,
  QUICK_COACH_PROMPTS,
  DAILY_ATHLETE_CHALLENGES,
} from "../data/aiCoachData";
import "./AICoach.css";

type TabMode = "generator" | "chat" | "nutrition" | "drills" | "calculators";

interface ChatMessage {
  id: string;
  sender: "user" | "coach";
  coachId?: string;
  text: string;
  timestamp: string;
  recommendedProductIds?: number[];
  drillTopic?: string;
}

let messageSeq = 0;
const nextMsgId = (prefix: string) => `${prefix}-${++messageSeq}`;

const AICoach: React.FC = () => {
  const { addToCart } = useCart();
  const [activeTab, setActiveTab] = useState<TabMode>("generator");

  // ==========================================
  // MODULE 1: WORKOUT & TRAINING PLAN GENERATOR STATE
  // ==========================================
  const [selectedSport, setSelectedSport] = useState<string>("Cricket");
  const [selectedGoal, setSelectedGoal] = useState<string>("power");
  const [selectedLevel, setSelectedLevel] = useState<string>("intermediate");
  const [selectedDays, setSelectedDays] = useState<number>(4);
  const [selectedEnv, setSelectedEnv] = useState<string>("mixed");
  const [completedDrills, setCompletedDrills] = useState<Record<string, boolean>>({});
  const planGenerated = true;
  const [planCopied, setPlanCopied] = useState<boolean>(false);

  // Toggle drill completion in current plan
  const toggleDrillComplete = (drillKey: string) => {
    setCompletedDrills((prev) => ({
      ...prev,
      [drillKey]: !prev[drillKey],
    }));
  };

  // Compute active training plan based on selected sport
  const currentPlan = useMemo(() => {
    const basePlan = TRAINING_PLANS_BY_SPORT[selectedSport] || TRAINING_PLANS_BY_SPORT["Cricket"];
    return basePlan;
  }, [selectedSport]);

  // Handle plan copy
  const handleCopyPlan = () => {
    const textToCopy = `GIGA AI SPORTS COACH - ${currentPlan.sport} Training Protocol\nLevel: ${selectedLevel.toUpperCase()} | Days: ${selectedDays} Days/Week\nGoal: ${currentPlan.goal}\n\nSchedule:\n${currentPlan.schedule
      .map(
        (day) =>
          `\n📌 ${day.dayName} (${day.estimatedTime})\nFocus: ${day.focus}\nWarmup: ${day.warmup.join(", ")}\nDrills:\n${day.mainDrills
            .map((d) => `  - ${d.name}: ${d.sets} of ${d.repsOrDuration} (Rest: ${d.rest}) - Note: ${d.coachingNote}`)
            .join("\n")}`
      )
      .join("\n")}\n\nGenerated by GIGA SPORTS AI COACH`;

    navigator.clipboard.writeText(textToCopy);
    setPlanCopied(true);
    setTimeout(() => setPlanCopied(false), 2500);
  };

  // Find gear items for current plan
  const relevantGearProducts = useMemo(() => {
    const gearCat = selectedSport.toLowerCase();
    const matches = products.filter(
      (p) =>
        p.category.toLowerCase().includes(gearCat) ||
        p.category.toLowerCase().includes("gym") ||
        p.category.toLowerCase().includes("running")
    );
    return matches.slice(0, 4);
  }, [selectedSport]);

  // ==========================================
  // MODULE 2: AI COACH CHAT STATE & LOGIC
  // ==========================================
  const [selectedPersonaId, setSelectedPersonaId] = useState<string>("vance");
  const [chatInput, setChatInput] = useState<string>("");
  const [voiceEnabled, setVoiceEnabled] = useState<boolean>(false);
  const [isTyping, setIsTyping] = useState<boolean>(false);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      id: "msg-init-1",
      sender: "coach",
      coachId: "vance",
      text: "⚡ **Coach Vance in your corner!** Welcome to the GIGA AI Performance Lab. What sport are we conquering today? Ask me anything about explosive power, bowling pace, football finishing, tactical setups, or pre-match nutrition!",
      timestamp: "Just now",
      recommendedProductIds: [1, 2, 5],
    },
  ]);

  const activePersona = useMemo(() => {
    return (
      COACH_PERSONAS.find((p) => p.id === selectedPersonaId) ||
      COACH_PERSONAS[0]
    );
  }, [selectedPersonaId]);

  // Trigger speech synthesis if enabled
  const speakText = (text: string) => {
    if (!voiceEnabled || !window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const cleanText = text.replace(/[*_#`[\]()]/g, "");
    const utterance = new SpeechSynthesisUtterance(cleanText);
    utterance.rate = 1.05;
    utterance.pitch = 1.0;
    window.speechSynthesis.speak(utterance);
  };

  const handleSendChat = (textToSend?: string) => {
    const messageQuery = textToSend || chatInput;
    if (!messageQuery.trim()) return;

    const userMsg: ChatMessage = {
      id: nextMsgId("user"),
      sender: "user",
      text: messageQuery,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setChatMessages((prev) => [...prev, userMsg]);
    if (!textToSend) setChatInput("");
    setIsTyping(true);

    // AI dynamic response synthesis
    setTimeout(() => {
      let coachReply: string;
      let matchedProductIds: number[];
      const queryLower = messageQuery.toLowerCase();

      // Check matched predefined prompts
      const matchedPrompt = QUICK_COACH_PROMPTS.find(
        (qp) =>
          queryLower.includes(qp.topic.toLowerCase()) ||
          qp.topic.toLowerCase().split(" ").some((w) => queryLower.includes(w))
      );

      if (matchedPrompt) {
        coachReply = matchedPrompt.reply;
        matchedProductIds = matchedPrompt.suggestedProducts || [1, 2, 5];
      } else if (queryLower.includes("cricket") || queryLower.includes("bat") || queryLower.includes("bowl")) {
        coachReply = `🏏 **${activePersona.name}'s Cricket Tactical Breakdown:**\n\n- **Mechanics:** Focus on the kinetic chain from back-foot gather through front-leg lockout. In batting, keep the top hand in command and align your head directly over the ball bounce.\n- **Drill:** 30 shadow drives daily with a 2-second hold at the apex of follow-through.\n- **Coach Cue:** *"Power is generated from the ground up through hip rotation, not raw arm tension."*\n\nNeed a specific bowling drill or bat balance advice?`;
        matchedProductIds = [1, 7];
      } else if (queryLower.includes("football") || queryLower.includes("shoot") || queryLower.includes("pass") || queryLower.includes("soccer")) {
        coachReply = `⚽ **${activePersona.name}'s Football Mastery Analysis:**\n\n- **Strike Precision:** Lock your ankle joint 100% rigid. Plant your standing foot 6 inches adjacent to the ball pointing directly at your target.\n- **Agility & First Touch:** Cushion incoming passes with a relaxed ankle to kill momentum into open space on touch one.\n- **Conditioning:** Repeat 15-second box-to-box sprints with 30s recovery to replicate 90-minute match intensity.`;
        matchedProductIds = [2, 6];
      } else if (queryLower.includes("badminton") || queryLower.includes("racket") || queryLower.includes("smash")) {
        coachReply = `🏸 **${activePersona.name}'s Badminton Speed & Power Strategy:**\n\n- **Pronation:** Forearm internal rotation delivers 60% of smash speed. Relax your grip until 0.05 seconds prior to shuttlecock impact.\n- **Footwork:** Scissor jump with your non-racket leg trailing to power your immediate recovery back to center T court.\n- **Endurance:** High-speed skipping rope sets to condition reactive calf elasticity.`;
        matchedProductIds = [3, 6];
      } else if (queryLower.includes("gym") || queryLower.includes("muscle") || queryLower.includes("workout") || queryLower.includes("weight")) {
        coachReply = `💪 **${activePersona.name}'s Strength & Hypertrophy Blueprint:**\n\n- **Progressive Overload:** Add either 1 rep or small weight increments every 7 to 10 days on your compound lifts (Squat, Deadlift, Dumbbell Press, Rows).\n- **Tempo Control:** 2-second lowering phase (eccentric) creates maximal micro-tears for muscle hypertrophy.\n- **Protein Target:** Consume 1.8g to 2.2g of quality protein per kg of bodyweight daily.`;
        matchedProductIds = [5, 6];
      } else if (queryLower.includes("run") || queryLower.includes("stamina") || queryLower.includes("speed") || queryLower.includes("pace")) {
        coachReply = `👟 **${activePersona.name}'s Aerobic & Cadence Coaching:**\n\n- **Cadence:** Maintain 175-185 strides per minute with light midfoot strikes beneath your center of mass.\n- **80/20 Rule:** Keep 80% of your weekly volume in easy Zone 2 conversational pace, and 20% in high-intensity threshold/interval repeats.\n- **Hydration:** Replenish 500ml water + electrolytes for every 45 minutes of sustained aerobic output.`;
        matchedProductIds = [4, 6];
      } else if (queryLower.includes("food") || queryLower.includes("diet") || queryLower.includes("eat") || queryLower.includes("nutrition")) {
        coachReply = `🥗 **${activePersona.name}'s High-Performance Nutrition Fueling:**\n\n- **Pre-Game (3 Hours Out):** Low-glycemic carbs (oats, brown rice, sweet potato) + lean protein (chicken/eggs/whey) + minimal fats.\n- **Post-Game (Within 45 Mins):** 25-30g fast protein + 40-60g simple carbohydrates to replenish muscle glycogen stores and halt cortisol breakdown.\n- **Hydration:** Track your urine color—aim for pale straw yellow.`;
        matchedProductIds = [8, 6];
      } else {
        coachReply = `⚡ **${activePersona.name}'s Athlete Directive:**\n\nI analyzed your inquiry: *"${messageQuery}"*.\n\nKey Action Steps:\n1. **Kinetic Consistency:** Master the fundamental movement pattern with bodyweight before adding load or match intensity.\n2. **Recovery Optimization:** Muscle growth and skill neural pathways are built during 8 hours of quality deep sleep, not during the workout itself.\n3. **Equipment Synergy:** Using proper tournament-grade gear significantly reduces injury risks and optimizes kinetic transfer.\n\nAsk me about any specific drill, biomechanics correction, or sport routine!`;
        matchedProductIds = [1, 2, 5];
      }

      const coachMsg: ChatMessage = {
        id: nextMsgId("coach"),
        sender: "coach",
        coachId: activePersona.id,
        text: coachReply,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        recommendedProductIds: matchedProductIds,
      };

      setChatMessages((prev) => [...prev, coachMsg]);
      setIsTyping(false);
      speakText(coachReply);
    }, 850);
  };

  // ==========================================
  // MODULE 3: NUTRITION & HYDRATION CALCULATOR
  // ==========================================
  const [weightKg, setWeightKg] = useState<number>(72);
  const [heightCm, setHeightCm] = useState<number>(178);
  const [athleteAge, setAthleteAge] = useState<number>(24);
  const [gender, setGender] = useState<"male" | "female">("male");
  const [activityIntensity, setActivityIntensity] = useState<"moderate" | "high" | "match-day">("high");
  const [nutritionGoal, setNutritionGoal] = useState<"lean-muscle" | "fat-loss" | "endurance" | "maintain">("lean-muscle");

  const nutritionResults = useMemo(() => {
    // Harris-Benedict BMR
    const bmr =
      gender === "male"
        ? 88.362 + 13.397 * weightKg + 4.799 * heightCm - 5.677 * athleteAge
        : 447.593 + 9.247 * weightKg + 3.098 * heightCm - 4.33 * athleteAge;

    // Activity Multiplier
    const multMap = {
      moderate: 1.55,
      high: 1.75,
      "match-day": 1.95,
    };
    const tdee = Math.round(bmr * multMap[activityIntensity]);

    // Target Calories
    let targetCalories = tdee;
    if (nutritionGoal === "lean-muscle") targetCalories = tdee + 350;
    if (nutritionGoal === "fat-loss") targetCalories = tdee - 450;
    if (nutritionGoal === "endurance") targetCalories = tdee + 250;

    // Macro distribution
    const proteinGrams = Math.round(weightKg * (nutritionGoal === "lean-muscle" ? 2.2 : 1.9));
    const fatsGrams = Math.round((targetCalories * 0.25) / 9);
    const carbsCalories = targetCalories - proteinGrams * 4 - fatsGrams * 9;
    const carbsGrams = Math.max(80, Math.round(carbsCalories / 4));

    // Hydration calculation: 35ml per kg + workout fluid replenishment
    const baseWaterLiters = (weightKg * 0.038).toFixed(1);
    const matchDayWaterLiters = (Number(baseWaterLiters) + 1.2).toFixed(1);

    return {
      bmr: Math.round(bmr),
      tdee,
      targetCalories,
      proteinGrams,
      fatsGrams,
      carbsGrams,
      baseWaterLiters,
      matchDayWaterLiters,
    };
  }, [weightKg, heightCm, athleteAge, gender, activityIntensity, nutritionGoal]);

  // ==========================================
  // MODULE 4: BIOMECHANICS & DRILLS MASTER STATE
  // ==========================================
  const [selectedDrillSport, setSelectedDrillSport] = useState<string>("All");
  const [selfAssessScores, setSelfAssessScores] = useState<Record<string, number>>({});

  const filteredDrills = useMemo(() => {
    if (selectedDrillSport === "All") return PRO_DRILLS;
    return PRO_DRILLS.filter(
      (d) => d.sport.toLowerCase() === selectedDrillSport.toLowerCase()
    );
  }, [selectedDrillSport]);

  const handleScoreDrill = (drillId: string, score: number) => {
    setSelfAssessScores((prev) => ({
      ...prev,
      [drillId]: score,
    }));
  };

  // ==========================================
  // MODULE 5: PERFORMANCE CALCULATORS & STREAK
  // ==========================================
  // 1RM Calculator
  const [liftWeight, setLiftWeight] = useState<number>(80);
  const [liftReps, setLiftReps] = useState<number>(5);

  const calculated1RM = useMemo(() => {
    if (liftWeight > 0 && liftReps > 0) {
      // Epley formula: 1RM = weight * (1 + reps / 30)
      return Math.round(liftWeight * (1 + liftReps / 30));
    }
    return 0;
  }, [liftWeight, liftReps]);

  // Running Pace Calculator
  const [targetDistanceKm, setTargetDistanceKm] = useState<number>(5);
  const [targetMinutes, setTargetMinutes] = useState<number>(25);

  const runningPaceResult = useMemo(() => {
    if (targetDistanceKm <= 0 || targetMinutes <= 0) return { pacePerKm: "0:00", speedKmh: "0" };
    const paceDecimal = targetMinutes / targetDistanceKm;
    const paceMin = Math.floor(paceDecimal);
    const paceSec = Math.round((paceDecimal - paceMin) * 60);
    const speedKmh = (targetDistanceKm / (targetMinutes / 60)).toFixed(1);
    return {
      pacePerKm: `${paceMin}:${paceSec < 10 ? "0" : ""}${paceSec}`,
      speedKmh,
    };
  }, [targetDistanceKm, targetMinutes]);

  // Daily Athlete Streak (persisted in localStorage)
  const [streakDays, setStreakDays] = useState<number>(() => {
    try {
      const saved = localStorage.getItem("giga_athlete_streak");
      return saved ? parseInt(saved, 10) : 3;
    } catch {
      return 3;
    }
  });
  const [completedChallenges, setCompletedChallenges] = useState<Record<number, boolean>>({});

  const handleCompleteChallenge = (id: number) => {
    if (!completedChallenges[id]) {
      const nextStreak = streakDays + 1;
      setStreakDays(nextStreak);
      setCompletedChallenges((prev) => ({ ...prev, [id]: true }));
      try {
        localStorage.setItem("giga_athlete_streak", nextStreak.toString());
      } catch (err) {
        console.error(err);
      }
    }
  };

  const getCleanImageUrl = (image: string): string => {
    if (!image) return "";
    const match = image.match(/\]\((.*?)\)/);
    if (match && match[1]) return match[1];
    return image;
  };

  return (
    <main className="ai-coach-page">
      {/* =========================================================
          HERO BANNER & TITLE
          ========================================================= */}
      <section className="ai-coach-hero">
        <div className="container">
          <div className="ai-coach-hero-inner">
            <div className="ai-hero-badge-wrap">
              <span className="ai-live-pulse-badge">
                <span className="pulse-dot"></span>
                LIVE AI COACH ONLINE
              </span>
              <span className="ai-hero-sub-pill">
                <FaBolt /> PRO ATHLETE INTELLIGENCE
              </span>
            </div>

            <h1 className="ai-coach-main-title">
              GIGA <span>AI Sports Coach</span> Studio
            </h1>

            <p className="ai-coach-lead">
              Elevate your athletic performance with personalized sport routines, real-time AI tactical coaching,
              biomechanics drill breakdowns, match nutrition formulas, and equipment matching.
            </p>

            {/* Quick Hero Stat Chips */}
            <div className="ai-hero-stats-bar">
              <div className="ai-stat-chip">
                <FaTrophy className="chip-icon gold" />
                <div>
                  <strong>10,000+</strong>
                  <span>Athletic Drills</span>
                </div>
              </div>
              <div className="ai-stat-chip">
                <FaFire className="chip-icon orange" />
                <div>
                  <strong>{streakDays}-Day Streak</strong>
                  <span>Athlete Consistency</span>
                </div>
              </div>
              <div className="ai-stat-chip">
                <FaHeartbeat className="chip-icon red" />
                <div>
                  <strong>99.4%</strong>
                  <span>Accuracy & Safety</span>
                </div>
              </div>
              <div className="ai-stat-chip">
                <FaRobot className="chip-icon blue" />
                <div>
                  <strong>4 Pro Personas</strong>
                  <span>Specialized Mentors</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* =========================================================
          INTERACTIVE MODULES NAVIGATION TABS
          ========================================================= */}
      <section className="ai-tabs-navigation-section">
        <div className="container">
          <div className="ai-modules-tab-bar">
            <button
              type="button"
              className={`ai-tab-btn ${activeTab === "generator" ? "active" : ""}`}
              onClick={() => setActiveTab("generator")}
            >
              <FaDumbbell />
              <span>Workout Generator</span>
            </button>

            <button
              type="button"
              className={`ai-tab-btn ${activeTab === "chat" ? "active" : ""}`}
              onClick={() => setActiveTab("chat")}
            >
              <FaComments />
              <span>24/7 AI Coach Chat</span>
            </button>

            <button
              type="button"
              className={`ai-tab-btn ${activeTab === "nutrition" ? "active" : ""}`}
              onClick={() => setActiveTab("nutrition")}
            >
              <FaAppleAlt />
              <span>Nutrition & Hydration</span>
            </button>

            <button
              type="button"
              className={`ai-tab-btn ${activeTab === "drills" ? "active" : ""}`}
              onClick={() => setActiveTab("drills")}
            >
              <FaBullseye />
              <span>Biomechanics & Drills</span>
            </button>

            <button
              type="button"
              className={`ai-tab-btn ${activeTab === "calculators" ? "active" : ""}`}
              onClick={() => setActiveTab("calculators")}
            >
              <FaCalculator />
              <span>Athlete Calculators</span>
            </button>
          </div>
        </div>
      </section>

      {/* =========================================================
          TAB 1: WORKOUT & TRAINING PLAN GENERATOR
          ========================================================= */}
      {activeTab === "generator" && (
        <section className="container py-5">
          <div className="ai-panel-glass">
            <div className="panel-header-badge">
              <span className="badge-tag">MODULE 01</span>
              <h2>🏋️ AI Personalized Training Protocol Generator</h2>
              <p>Configure your sport, training goals, and schedule to build a customized high-performance routine.</p>
            </div>

            {/* Form Controls */}
            <div className="ai-generator-controls-grid">
              {/* Sport Selector */}
              <div className="gen-control-group">
                <label htmlFor="gen-sport">🏆 Select Your Sport</label>
                <select
                  id="gen-sport"
                  value={selectedSport}
                  onChange={(e) => setSelectedSport(e.target.value)}
                  className="ai-select-input"
                >
                  <option value="Cricket">🏏 Cricket (Batting & Pace Bowling)</option>
                  <option value="Football">⚽ Football (Finishing & Agility)</option>
                  <option value="Badminton">🏸 Badminton (Smash & Fast Footwork)</option>
                  <option value="Gym Equipment">💪 Gym & Athletic Hypertrophy</option>
                  <option value="Running">👟 Running & Aerobic Stamina</option>
                </select>
              </div>

              {/* Goal Selector */}
              <div className="gen-control-group">
                <label htmlFor="gen-goal">🎯 Primary Athlete Goal</label>
                <select
                  id="gen-goal"
                  value={selectedGoal}
                  onChange={(e) => setSelectedGoal(e.target.value)}
                  className="ai-select-input"
                >
                  <option value="power">⚡ Explosive Power & Velocity</option>
                  <option value="speed">🏃 Agility & Rapid Footwork</option>
                  <option value="stamina">🔥 Match Endurance & Stamina</option>
                  <option value="rehab">🛡️ Injury Prevention & Joint Armor</option>
                </select>
              </div>

              {/* Experience Level */}
              <div className="gen-control-group">
                <label htmlFor="gen-level">📊 Experience Level</label>
                <select
                  id="gen-level"
                  value={selectedLevel}
                  onChange={(e) => setSelectedLevel(e.target.value)}
                  className="ai-select-input"
                >
                  <option value="beginner">🌱 Grassroots / Beginner</option>
                  <option value="intermediate">⭐ Club / Semi-Pro</option>
                  <option value="advanced">🏆 League / Elite Athlete</option>
                </select>
              </div>

              {/* Schedule Days */}
              <div className="gen-control-group">
                <label htmlFor="gen-days">📅 Days per Week</label>
                <select
                  id="gen-days"
                  value={selectedDays}
                  onChange={(e) => setSelectedDays(Number(e.target.value))}
                  className="ai-select-input"
                >
                  <option value={3}>3 Days / Week (Balanced)</option>
                  <option value={4}>4 Days / Week (Recommended)</option>
                  <option value={5}>5 Days / Week (Intense Pro)</option>
                </select>
              </div>

              {/* Training Location */}
              <div className="gen-control-group">
                <label htmlFor="gen-env">📍 Training Environment</label>
                <select
                  id="gen-env"
                  value={selectedEnv}
                  onChange={(e) => setSelectedEnv(e.target.value)}
                  className="ai-select-input"
                >
                  <option value="mixed">🏟️ Pitch / Turf + Home Gym</option>
                  <option value="outdoor">🌿 Outdoor Ground / Track Only</option>
                  <option value="gym">🏋️ Full Commercial Gym</option>
                  <option value="home">🏠 Home Bodyweight & Bands</option>
                </select>
              </div>
            </div>

            {/* Generated Plan Output */}
            {planGenerated && currentPlan && (
              <div className="ai-plan-output-container">
                <div className="plan-meta-banner">
                  <div className="plan-meta-left">
                    <span className="plan-sport-tag">{currentPlan.sport.toUpperCase()}</span>
                    <h3>{currentPlan.goal}</h3>
                    <p className="plan-desc">{currentPlan.overview}</p>
                    <div className="plan-nutrition-alert">
                      <FaLightbulb className="alert-bulb-icon" />
                      <span><strong>Pro Coach Nutrition Tip:</strong> {currentPlan.nutritionTip}</span>
                    </div>
                  </div>

                  <div className="plan-meta-actions">
                    <button type="button" className="btn-copy-plan" onClick={handleCopyPlan}>
                      {planCopied ? <FaCheck /> : <FaCopy />}
                      {planCopied ? "Copied to Clipboard!" : "Copy Full Protocol"}
                    </button>
                  </div>
                </div>

                {/* Day-by-Day Timetable */}
                <div className="plan-days-grid">
                  {currentPlan.schedule.slice(0, selectedDays).map((day, dIdx) => (
                    <div className="plan-day-card" key={dIdx}>
                      <div className="day-card-header">
                        <div>
                          <span className="day-number">DAY 0{dIdx + 1}</span>
                          <h4>{day.dayName}</h4>
                          <span className="day-focus">{day.focus}</span>
                        </div>
                        <div className="day-intensity-badge">
                          <span className={`intensity-dot ${day.intensity.toLowerCase()}`}></span>
                          {day.intensity} Effort • {day.estimatedTime}
                        </div>
                      </div>

                      {/* Warmup */}
                      <div className="day-section-block">
                        <h5 className="sub-heading-title">🔥 Dynamic Warm-Up & Activation</h5>
                        <ul className="warmup-list">
                          {day.warmup.map((wItem, wIdx) => (
                            <li key={wIdx}>{wItem}</li>
                          ))}
                        </ul>
                      </div>

                      {/* Main Drills with interactive completion */}
                      <div className="day-section-block">
                        <h5 className="sub-heading-title">🎯 Core Athletic Drills & Reps</h5>
                        <div className="drills-table">
                          {day.mainDrills.map((drill, drillIdx) => {
                            const drillKey = `${dIdx}-${drillIdx}`;
                            const isDone = !!completedDrills[drillKey];

                            return (
                              <div
                                className={`drill-row-item ${isDone ? "completed" : ""}`}
                                key={drillIdx}
                                onClick={() => toggleDrillComplete(drillKey)}
                              >
                                <button type="button" className="drill-check-btn" aria-label="Toggle Complete">
                                  {isDone ? <FaCheckSquare className="icon-checked" /> : <FaSquare className="icon-unchecked" />}
                                </button>
                                <div className="drill-details">
                                  <div className="drill-title-row">
                                    <strong>{drill.name}</strong>
                                    <span className="drill-metrics-badge">
                                      {drill.sets} • {drill.repsOrDuration} • Rest: {drill.rest}
                                    </span>
                                  </div>
                                  <p className="drill-coaching-note">
                                    <em>Coach Cue:</em> {drill.coachingNote}
                                  </p>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>

                      {/* Cooldown */}
                      <div className="day-section-block">
                        <h5 className="sub-heading-title">🧘 Recovery & Decompression</h5>
                        <ul className="cooldown-list">
                          {day.cooldown.map((cItem, cIdx) => (
                            <li key={cIdx}>{cItem}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Recommended Gear Matches from Shop */}
                <div className="plan-gear-recommendations">
                  <div className="gear-rec-header">
                    <div>
                      <span className="section-pill">GIGA SPORTS INTEGRATION</span>
                      <h3>Recommended Gear for this Protocol</h3>
                      <p>Equip yourself with the official sports gear recommended by our AI coach for maximum performance.</p>
                    </div>
                  </div>

                  <div className="gear-products-grid">
                    {relevantGearProducts.map((product) => (
                      <div className="ai-gear-item-card" key={product.id}>
                        <div className="gear-card-img-wrap">
                          {product.badge && <span className="gear-badge">{product.badge}</span>}
                          <img src={getCleanImageUrl(product.image)} alt={product.name} />
                        </div>
                        <div className="gear-card-body">
                          <span className="gear-category">{product.category}</span>
                          <h5>{product.name}</h5>
                          <div className="gear-price-row">
                            <span className="price-tag">Rs. {product.price.toLocaleString()}</span>
                            {product.rating && (
                              <span className="rating-tag">
                                <FaStar /> {product.rating}
                              </span>
                            )}
                          </div>
                          <div className="gear-card-actions">
                            <Link to={`/products/${product.id}`} className="btn-view-product">
                              View Specs
                            </Link>
                            <button
                              type="button"
                              className="btn-add-gear-cart"
                              onClick={() => addToCart(product)}
                            >
                              <FaShoppingCart /> Add to Cart
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </section>
      )}

      {/* =========================================================
          TAB 2: 24/7 AI COACH CONVERSATIONAL ASSISTANT
          ========================================================= */}
      {activeTab === "chat" && (
        <section className="container py-5">
          <div className="ai-chat-studio-container">
            {/* Left Column: Coach Persona Selector */}
            <div className="coach-personas-sidebar">
              <div className="sidebar-title">
                <FaRobot />
                <h3>Select Your Mentor</h3>
              </div>
              <p className="sidebar-sub">Choose a specialized AI sports persona tailored to your coaching style.</p>

              <div className="personas-list">
                {COACH_PERSONAS.map((persona) => (
                  <div
                    className={`persona-card-item ${persona.id === selectedPersonaId ? "active" : ""}`}
                    key={persona.id}
                    onClick={() => {
                      setSelectedPersonaId(persona.id);
                      const switchMsg: ChatMessage = {
                        id: `switch-${Date.now()}`,
                        sender: "coach",
                        coachId: persona.id,
                        text: `**${persona.name} (${persona.badge}) active:**\n"${persona.greeting}"`,
                        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
                      };
                      setChatMessages((prev) => [...prev, switchMsg]);
                      speakText(persona.greeting);
                    }}
                  >
                    <div className="persona-avatar-circle">{persona.avatar}</div>
                    <div className="persona-info">
                      <div className="persona-name-row">
                        <strong>{persona.name}</strong>
                        <span className="persona-badge-tag">{persona.badge}</span>
                      </div>
                      <span className="persona-specialty">{persona.specialty}</span>
                      <p className="persona-quote">"{persona.quote}"</p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Voice Readout Toggle */}
              <div className="voice-toggle-card">
                <div className="voice-info">
                  {voiceEnabled ? <FaVolumeUp className="voice-icon-on" /> : <FaVolumeMute className="voice-icon-off" />}
                  <div>
                    <strong>AI Voice Narration</strong>
                    <span>{voiceEnabled ? "Voice Enabled" : "Voice Muted"}</span>
                  </div>
                </div>
                <button
                  type="button"
                  className={`btn-voice-toggle ${voiceEnabled ? "active" : ""}`}
                  onClick={() => setVoiceEnabled(!voiceEnabled)}
                >
                  {voiceEnabled ? "Disable" : "Enable"}
                </button>
              </div>
            </div>

            {/* Right Column: Interactive Chat Box */}
            <div className="coach-chat-main-box">
              {/* Chat Header */}
              <div className="chat-box-header">
                <div className="active-coach-meta">
                  <div className="coach-active-avatar">{activePersona.avatar}</div>
                  <div>
                    <h4>{activePersona.name}</h4>
                    <span className="coach-status-online">
                      <span className="live-dot"></span> {activePersona.title}
                    </span>
                  </div>
                </div>

                <div className="chat-actions-top">
                  <button
                    type="button"
                    className="btn-clear-chat"
                    onClick={() =>
                      setChatMessages([
                        {
                          id: `msg-reset-${Date.now()}`,
                          sender: "coach",
                          coachId: activePersona.id,
                          text: `⚡ Chat session refreshed with **${activePersona.name}**. How can I help optimize your match day performance?`,
                          timestamp: "Just now",
                          recommendedProductIds: [1, 2, 5],
                        },
                      ])
                    }
                  >
                    <FaUndo /> Reset Chat
                  </button>
                </div>
              </div>

              {/* Quick Action Prompt Chips */}
              <div className="quick-prompt-chips-bar">
                <span className="chips-label">Quick Prompts:</span>
                <div className="chips-scroll">
                  {QUICK_COACH_PROMPTS.map((qp, qIdx) => (
                    <button
                      type="button"
                      className="prompt-chip-btn"
                      key={qIdx}
                      onClick={() => handleSendChat(qp.prompt)}
                    >
                      <span>{qp.icon}</span> {qp.topic}
                    </button>
                  ))}
                </div>
              </div>

              {/* Chat Messages Stream */}
              <div className="chat-messages-stream">
                {chatMessages.map((msg) => (
                  <div className={`chat-message-bubble ${msg.sender}`} key={msg.id}>
                    {msg.sender === "coach" && (
                      <div className="msg-sender-tag">
                        <span className="coach-mini-avatar">
                          {COACH_PERSONAS.find((p) => p.id === msg.coachId)?.avatar || "⚡"}
                        </span>
                        <span className="coach-mini-name">
                          {COACH_PERSONAS.find((p) => p.id === msg.coachId)?.name || "GIGA AI Coach"}
                        </span>
                        <span className="msg-time">{msg.timestamp}</span>
                      </div>
                    )}

                    <div className="msg-content-body">
                      {msg.text.split("\n").map((line, lIdx) => {
                        if (line.startsWith("### ")) {
                          return <h4 key={lIdx} className="chat-h4">{line.replace("### ", "")}</h4>;
                        }
                        if (line.startsWith("## ")) {
                          return <h3 key={lIdx} className="chat-h3">{line.replace("## ", "")}</h3>;
                        }
                        if (line.startsWith("1. ") || line.startsWith("2. ") || line.startsWith("3. ") || line.startsWith("4. ")) {
                          return <div key={lIdx} className="chat-list-num">{line}</div>;
                        }
                        if (line.startsWith("- ")) {
                          return <div key={lIdx} className="chat-list-bullet">{line}</div>;
                        }
                        return <p key={lIdx} className="chat-para">{line}</p>;
                      })}
                    </div>

                    {/* Show suggested gear cards if available */}
                    {msg.recommendedProductIds && msg.recommendedProductIds.length > 0 && (
                      <div className="chat-suggested-gear-box">
                        <span className="suggested-gear-title">
                          <FaShoppingCart /> Recommended Equipment from GIGA SPORTS:
                        </span>
                        <div className="suggested-gear-items">
                          {products
                            .filter((p) => msg.recommendedProductIds?.includes(p.id))
                            .map((p) => (
                              <div className="mini-gear-pill" key={p.id}>
                                <img src={getCleanImageUrl(p.image)} alt={p.name} />
                                <div className="mini-gear-info">
                                  <strong>{p.name}</strong>
                                  <span>Rs. {p.price.toLocaleString()}</span>
                                </div>
                                <button
                                  type="button"
                                  className="btn-quick-add"
                                  onClick={() => addToCart(p)}
                                >
                                  + Cart
                                </button>
                              </div>
                            ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}

                {isTyping && (
                  <div className="chat-message-bubble coach typing-bubble">
                    <div className="typing-dots">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                    <em>{activePersona.name} is formulating tactical advice...</em>
                  </div>
                )}
              </div>

              {/* Chat Input Bar */}
              <form
                className="chat-input-container"
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSendChat();
                }}
              >
                <input
                  type="text"
                  placeholder={`Ask ${activePersona.name} about drills, mechanics, gear or tactics...`}
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  className="chat-text-input"
                />
                <button type="submit" className="btn-chat-send" disabled={!chatInput.trim() || isTyping}>
                  <FaPaperPlane />
                  <span>Send</span>
                </button>
              </form>
            </div>
          </div>
        </section>
      )}

      {/* =========================================================
          TAB 3: ATHLETE NUTRITION & HYDRATION CALCULATOR
          ========================================================= */}
      {activeTab === "nutrition" && (
        <section className="container py-5">
          <div className="ai-panel-glass">
            <div className="panel-header-badge">
              <span className="badge-tag">MODULE 03</span>
              <h2>🥗 AI Athlete Nutrition & Match Fueling Engine</h2>
              <p>Calculate your exact scientific calorie, macronutrient, and hydration targets tailored for training volume.</p>
            </div>

            <div className="nutrition-grid-layout">
              {/* Inputs Form */}
              <div className="nutrition-form-card">
                <h3>Athlete Biometric Inputs</h3>

                <div className="nut-form-group">
                  <label>Gender</label>
                  <div className="nut-radio-group">
                    <button
                      type="button"
                      className={`nut-pill-radio ${gender === "male" ? "active" : ""}`}
                      onClick={() => setGender("male")}
                    >
                      Male Athlete
                    </button>
                    <button
                      type="button"
                      className={`nut-pill-radio ${gender === "female" ? "active" : ""}`}
                      onClick={() => setGender("female")}
                    >
                      Female Athlete
                    </button>
                  </div>
                </div>

                <div className="nut-fields-row">
                  <div className="nut-form-group">
                    <label htmlFor="nut-weight">Weight (kg)</label>
                    <input
                      id="nut-weight"
                      type="number"
                      min={35}
                      max={180}
                      value={weightKg}
                      onChange={(e) => setWeightKg(Number(e.target.value))}
                      className="ai-select-input"
                    />
                  </div>
                  <div className="nut-form-group">
                    <label htmlFor="nut-height">Height (cm)</label>
                    <input
                      id="nut-height"
                      type="number"
                      min={120}
                      max={230}
                      value={heightCm}
                      onChange={(e) => setHeightCm(Number(e.target.value))}
                      className="ai-select-input"
                    />
                  </div>
                  <div className="nut-form-group">
                    <label htmlFor="nut-age">Age (yrs)</label>
                    <input
                      id="nut-age"
                      type="number"
                      min={10}
                      max={85}
                      value={athleteAge}
                      onChange={(e) => setAthleteAge(Number(e.target.value))}
                      className="ai-select-input"
                    />
                  </div>
                </div>

                <div className="nut-form-group">
                  <label htmlFor="nut-intensity">Training Output / Intensity</label>
                  <select
                    id="nut-intensity"
                    value={activityIntensity}
                    onChange={(e) =>
                      setActivityIntensity(
                        e.target.value as "moderate" | "high" | "match-day"
                      )
                    }
                    className="ai-select-input"
                  >
                    <option value="moderate">Moderate Training (3-4x weekly light drills)</option>
                    <option value="high">High Intensity (5-6x weekly hard training)</option>
                    <option value="match-day">Competitive Match Day (Tournament volume)</option>
                  </select>
                </div>

                <div className="nut-form-group">
                  <label htmlFor="nut-goal">Primary Physical Objective</label>
                  <select
                    id="nut-goal"
                    value={nutritionGoal}
                    onChange={(e) =>
                      setNutritionGoal(
                        e.target.value as
                          | "lean-muscle"
                          | "fat-loss"
                          | "endurance"
                          | "maintain"
                      )
                    }
                    className="ai-select-input"
                  >
                    <option value="lean-muscle">Build Lean Muscle & Power (+350 kcal)</option>
                    <option value="fat-loss">Cut Fat & Increase Agility (-450 kcal)</option>
                    <option value="endurance">Endurance & Glycogen Replenishment (+250 kcal)</option>
                    <option value="maintain">Maintain Peak Performance Weight (Maintenance)</option>
                  </select>
                </div>
              </div>

              {/* Calculated Outputs */}
              <div className="nutrition-results-card">
                <h3>Scientific Target Breakdown</h3>

                <div className="calorie-summary-box">
                  <div className="calorie-stat">
                    <span className="cal-label">Daily Energy Target</span>
                    <strong className="cal-val">{nutritionResults.targetCalories.toLocaleString()}</strong>
                    <span className="cal-unit">kcal / day</span>
                  </div>
                  <div className="cal-divider"></div>
                  <div className="calorie-stat">
                    <span className="cal-label">Baseline BMR</span>
                    <strong className="cal-val-sub">{nutritionResults.bmr.toLocaleString()}</strong>
                    <span className="cal-unit">kcal at rest</span>
                  </div>
                </div>

                {/* Macronutrient Bars */}
                <div className="macros-breakdown-list">
                  <div className="macro-row-card protein">
                    <div className="macro-header-row">
                      <span className="macro-name">🍗 Protein (Muscle Repair & Power)</span>
                      <strong>{nutritionResults.proteinGrams}g</strong>
                    </div>
                    <div className="macro-progress-bar">
                      <div className="bar-fill protein-fill" style={{ width: "35%" }}></div>
                    </div>
                    <span className="macro-sub-info">{(nutritionResults.proteinGrams / weightKg).toFixed(1)}g per kg bodyweight</span>
                  </div>

                  <div className="macro-row-card carbs">
                    <div className="macro-header-row">
                      <span className="macro-name">⚡ Carbohydrates (Match Fuel & Glycogen)</span>
                      <strong>{nutritionResults.carbsGrams}g</strong>
                    </div>
                    <div className="macro-progress-bar">
                      <div className="bar-fill carbs-fill" style={{ width: "50%" }}></div>
                    </div>
                    <span className="macro-sub-info">Primary substrate for high-intensity sprinting</span>
                  </div>

                  <div className="macro-row-card fats">
                    <div className="macro-header-row">
                      <span className="macro-name">🥑 Essential Fats (Hormone Health)</span>
                      <strong>{nutritionResults.fatsGrams}g</strong>
                    </div>
                    <div className="macro-progress-bar">
                      <div className="bar-fill fats-fill" style={{ width: "25%" }}></div>
                    </div>
                    <span className="macro-sub-info">25% of total caloric distribution</span>
                  </div>
                </div>

                {/* Hydration Guidance */}
                <div className="hydration-target-box">
                  <div className="hyd-left">
                    <FaBolt className="hyd-icon" />
                    <div>
                      <h4>Target Hydration</h4>
                      <p>Non-training: <strong>{nutritionResults.baseWaterLiters} Liters</strong> | Match Day: <strong>{nutritionResults.matchDayWaterLiters} Liters</strong></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* 4-Phase Match Day Fueling Timeline */}
            <div className="fueling-timeline-section">
              <h3 className="timeline-title">⏱️ 4-Phase Match Day Nutrition Timeline</h3>

              <div className="timeline-cards-row">
                <div className="timeline-phase-card">
                  <span className="phase-badge">PHASE 1</span>
                  <h4>3 Hours Pre-Match</h4>
                  <p className="phase-desc">Complex carbs + lean protein. Low in fat and fiber to prevent gastric distress.</p>
                  <div className="phase-meal-example">
                    <strong>Example Meal:</strong> Oatmeal with banana, honey & scoop of whey protein OR Grilled chicken breast with white rice.
                  </div>
                </div>

                <div className="timeline-phase-card">
                  <span className="phase-badge">PHASE 2</span>
                  <h4>45 Mins Pre-Match</h4>
                  <p className="phase-desc">Fast glycemic boost + electrolyte preload.</p>
                  <div className="phase-meal-example">
                    <strong>Example:</strong> 1 ripe banana + 400ml water with electrolyte salt tab.
                  </div>
                </div>

                <div className="timeline-phase-card">
                  <span className="phase-badge">PHASE 3</span>
                  <h4>During Match Intervals</h4>
                  <p className="phase-desc">Sustained hydration and blood glucose maintenance.</p>
                  <div className="phase-meal-example">
                    <strong>Example:</strong> 150ml isotonic sports drink every 15-20 mins during breaks.
                  </div>
                </div>

                <div className="timeline-phase-card">
                  <span className="phase-badge">PHASE 4</span>
                  <h4>Within 45 Mins Post-Match</h4>
                  <p className="phase-desc">Anabolic window for rapid glycogen and myofibrillar repair.</p>
                  <div className="phase-meal-example">
                    <strong>Example:</strong> 30g fast protein shake + 50g simple carbs (dates, dextrose or fruit juice).
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* =========================================================
          TAB 4: BIOMECHANICS & DRILLS MASTER
          ========================================================= */}
      {activeTab === "drills" && (
        <section className="container py-5">
          <div className="ai-panel-glass">
            <div className="panel-header-badge">
              <span className="badge-tag">MODULE 04</span>
              <h2>🎯 Pro Biomechanics & Drills Masterclass</h2>
              <p>Step-by-step kinetic breakdowns, coaching cues, common mistake audits, and interactive self-scoring.</p>
            </div>

            {/* Sport Filter Tabs */}
            <div className="drills-filter-tabs">
              {["All", "Cricket", "Football", "Badminton", "Gym Equipment", "Running"].map((sportName) => (
                <button
                  type="button"
                  key={sportName}
                  className={`drill-filter-btn ${selectedDrillSport === sportName ? "active" : ""}`}
                  onClick={() => setSelectedDrillSport(sportName)}
                >
                  {sportName}
                </button>
              ))}
            </div>

            {/* Drills Grid */}
            <div className="drills-catalog-grid">
              {filteredDrills.map((drill) => {
                const currentScore = selfAssessScores[drill.id] || 0;

                return (
                  <div className="drill-pro-card" key={drill.id}>
                    <div className="drill-card-top">
                      <div className="drill-badges-row">
                        <span className="drill-sport-pill">{drill.sport}</span>
                        <span className={`drill-diff-pill ${drill.difficulty.toLowerCase()}`}>
                          {drill.difficulty}
                        </span>
                      </div>
                      <h3>{drill.title}</h3>
                      <p className="drill-summary">{drill.summary}</p>
                    </div>

                    <div className="drill-card-stats-row">
                      <div>
                        <strong>Duration:</strong> {drill.duration}
                      </div>
                      <div>
                        <strong>Intensity:</strong> {drill.intensity}
                      </div>
                    </div>

                    {/* Step-by-Step Keys */}
                    <div className="drill-steps-preview">
                      <h5>🔑 Execution Steps:</h5>
                      <ol className="drill-steps-ol">
                        {drill.keySteps.map((step, sIdx) => (
                          <li key={sIdx}>{step}</li>
                        ))}
                      </ol>
                    </div>

                    {/* Coaching Cues */}
                    <div className="drill-cues-box">
                      <strong>⚡ Pro Coaching Cues:</strong>
                      <ul>
                        {drill.coachingCues.map((cue, cIdx) => (
                          <li key={cIdx}>"{cue}"</li>
                        ))}
                      </ul>
                    </div>

                    {/* Common Mistakes */}
                    <div className="drill-mistakes-box">
                      <strong>⚠️ Common Faults to Avoid:</strong>
                      <ul>
                        {drill.commonMistakes.map((mistake, mIdx) => (
                          <li key={mIdx}>{mistake}</li>
                        ))}
                      </ul>
                    </div>

                    {/* Interactive Self-Assessment Scoring */}
                    <div className="drill-self-assessment-box">
                      <div className="assess-header">
                        <span>Self-Assess Your Form:</span>
                        <strong>{currentScore > 0 ? `${currentScore} / 5 Stars` : "Not Rated"}</strong>
                      </div>
                      <div className="stars-rating-bar">
                        {[1, 2, 3, 4, 5].map((starVal) => (
                          <button
                            type="button"
                            key={starVal}
                            className={`star-score-btn ${currentScore >= starVal ? "active" : ""}`}
                            onClick={() => handleScoreDrill(drill.id, starVal)}
                          >
                            <FaStar />
                          </button>
                        ))}
                      </div>
                      {currentScore > 0 && currentScore <= 2 && (
                        <small className="score-feedback warning">
                          Coach Tip: Reduce speed by 50% and focus purely on balance and joint alignment before accelerating.
                        </small>
                      )}
                      {currentScore >= 3 && currentScore <= 4 && (
                        <small className="score-feedback info">
                          Solid mechanics! Increase rep cadence and add match pressure conditions.
                        </small>
                      )}
                      {currentScore === 5 && (
                        <small className="score-feedback success">
                          🏆 Master Form! Maintain this standard under tournament fatigue.
                        </small>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {/* =========================================================
          TAB 5: ATHLETE CALCULATORS & DAILY STREAK
          ========================================================= */}
      {activeTab === "calculators" && (
        <section className="container py-5">
          <div className="ai-panel-glass">
            <div className="panel-header-badge">
              <span className="badge-tag">MODULE 05</span>
              <h2>📊 Athlete Calculators & Daily Streak Arena</h2>
              <p>Calculate 1-Rep Max strength zones, running split paces, cricket bat specs, and complete daily challenges.</p>
            </div>

            <div className="calculators-flex-grid">
              {/* Calculator 1: One-Rep Max (1RM) */}
              <div className="calculator-widget-card">
                <div className="widget-header">
                  <FaDumbbell className="widget-icon" />
                  <div>
                    <h3>1-Rep Max (1RM) Strength Engine</h3>
                    <p>Calculate your estimated max lift and training percentage load zones.</p>
                  </div>
                </div>

                <div className="widget-body">
                  <div className="widget-inputs-row">
                    <div className="w-input-group">
                      <label htmlFor="lift-w">Weight Lifted (kg)</label>
                      <input
                        id="lift-w"
                        type="number"
                        min={1}
                        max={400}
                        value={liftWeight}
                        onChange={(e) => setLiftWeight(Number(e.target.value))}
                        className="ai-select-input"
                      />
                    </div>
                    <div className="w-input-group">
                      <label htmlFor="lift-r">Reps Completed</label>
                      <input
                        id="lift-r"
                        type="number"
                        min={1}
                        max={15}
                        value={liftReps}
                        onChange={(e) => setLiftReps(Number(e.target.value))}
                        className="ai-select-input"
                      />
                    </div>
                  </div>

                  <div className="one-rm-display">
                    <span className="one-rm-label">Estimated 100% 1RM:</span>
                    <strong className="one-rm-val">{calculated1RM} kg</strong>
                  </div>

                  <div className="percentage-zones-grid">
                    <div className="zone-pill">
                      <span>90% (Peak Power)</span>
                      <strong>{Math.round(calculated1RM * 0.9)} kg</strong>
                    </div>
                    <div className="zone-pill">
                      <span>80% (Hypertrophy)</span>
                      <strong>{Math.round(calculated1RM * 0.8)} kg</strong>
                    </div>
                    <div className="zone-pill">
                      <span>70% (Endurance)</span>
                      <strong>{Math.round(calculated1RM * 0.7)} kg</strong>
                    </div>
                    <div className="zone-pill">
                      <span>50% (Dynamic Warmup)</span>
                      <strong>{Math.round(calculated1RM * 0.5)} kg</strong>
                    </div>
                  </div>
                </div>
              </div>

              {/* Calculator 2: Running Pace & Split Calculator */}
              <div className="calculator-widget-card">
                <div className="widget-header">
                  <FaRunning className="widget-icon" />
                  <div>
                    <h3>Running Pace & Split Calculator</h3>
                    <p>Determine target pacing per kilometer and average velocity for any distance.</p>
                  </div>
                </div>

                <div className="widget-body">
                  <div className="widget-inputs-row">
                    <div className="w-input-group">
                      <label htmlFor="pace-dist">Target Distance (km)</label>
                      <select
                        id="pace-dist"
                        value={targetDistanceKm}
                        onChange={(e) => setTargetDistanceKm(Number(e.target.value))}
                        className="ai-select-input"
                      >
                        <option value={1}>1 km (Sprint / Time Trial)</option>
                        <option value={5}>5 km (Standard 5K Race)</option>
                        <option value={10}>10 km (Endurance Run)</option>
                        <option value={21.1}>21.1 km (Half Marathon)</option>
                      </select>
                    </div>
                    <div className="w-input-group">
                      <label htmlFor="pace-time">Goal Time (Minutes)</label>
                      <input
                        id="pace-time"
                        type="number"
                        min={3}
                        max={300}
                        value={targetMinutes}
                        onChange={(e) => setTargetMinutes(Number(e.target.value))}
                        className="ai-select-input"
                      />
                    </div>
                  </div>

                  <div className="pace-results-display">
                    <div className="pace-box">
                      <span>Required Split Pace</span>
                      <strong>{runningPaceResult.pacePerKm} / km</strong>
                    </div>
                    <div className="pace-box">
                      <span>Average Speed</span>
                      <strong>{runningPaceResult.speedKmh} km/h</strong>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Daily Athlete Challenges & Streak Arena */}
            <div className="streak-arena-section">
              <div className="streak-header-banner">
                <div className="streak-title-left">
                  <FaTrophy className="streak-trophy-icon" />
                  <div>
                    <h3>Daily Athlete Challenges & Streak Arena</h3>
                    <p>Complete daily athletic conditioning tasks to build consistency, level up your badge, and unlock athlete discounts.</p>
                  </div>
                </div>
                <div className="streak-counter-badge">
                  <FaFire />
                  <div>
                    <strong>{streakDays} DAYS</strong>
                    <span>Current Streak</span>
                  </div>
                </div>
              </div>

              <div className="challenges-list-grid">
                {DAILY_ATHLETE_CHALLENGES.map((ch) => {
                  const isFinished = !!completedChallenges[ch.id];

                  return (
                    <div className={`challenge-card-item ${isFinished ? "done" : ""}`} key={ch.id}>
                      <div className="challenge-top">
                        <span className="ch-day-pill">{ch.day} • {ch.sport}</span>
                        <span className="ch-xp-badge">+{ch.xp} XP</span>
                      </div>
                      <h4>{ch.title}</h4>
                      <p>{ch.task}</p>
                      <div className="challenge-footer">
                        <span className="ch-target-tag">Target: {ch.target}</span>
                        <button
                          type="button"
                          className={`btn-ch-action ${isFinished ? "completed" : ""}`}
                          disabled={isFinished}
                          onClick={() => handleCompleteChallenge(ch.id)}
                        >
                          {isFinished ? (
                            <>
                              <FaCheck /> Challenge Done!
                            </>
                          ) : (
                            <>Mark as Complete (+1 Day)</>
                          )}
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </section>
      )}
    </main>
  );
};

export default AICoach;
